all:
	flex -o simple-flex-code.c simple-flex-code.l 
	gcc -o simple-flex-code simple-flex-code.c
	./simple-flex-code input_files/input.txt   output_files/output.txt
	./simple-flex-code input_files/input_1.txt output_files/output_1.txt
	./simple-flex-code input_files/input_2.txt output_files/output_2.txt
	./simple-flex-code input_files/input_3.txt output_files/output_3.txt